### ISSUE TITLE
npmunbox always request uri

### ISSUE THREAD

**Issue by nexmohh** [arei/npmbox#61] opened 2016-08-15 11:03 UTC
Hello,

i updated my npmbox on both systems (Online and Offline Server) but i always get this failure:

 Unpacking /root/npmbox/forever.npmbox...
  Installing forever...
npm verb request uri https://registry.npmjs.org/forever
npm verb request no auth needed
npm info attempt registry request try #1 at 12:45:04
npm verb request id 82bbaf54d524ae73
npm http request GET https://registry.npmjs.org/forever
An error occurred while installing forever.
forever was not installed.
{ [Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443]
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'registry.npmjs.org',
  host: 'registry.npmjs.org',
  port: 443 }
  Done.

So what is the Problem?

**Comment by arei** [comment] 2016-08-15 11:17
For both systems, what version of node, what version of npm, what version of npmbox, what os (looks like Linux), what is flavor (Debian, mint, redhat, etc), what os version, anything else you can tell me?

**Comment by nexmohh** [comment] 2016-08-15 12:45
Online Server:

node: 5.12.0
npm 3.10.6
npmbox 4.0.0
OS Linux Debian Whezzy 7.11

Offline Server:

node: 5.12.0
npm 3.8.6
npmbox 4.0.0
OS Linux Debian Whezzy 7.8

**Comment by avrahamcool** [comment] 2016-09-04 11:25
same problem here.

node: 4.4.7
npm 3.10.6
npmbox 4.0.0
OS: windows 10

**Comment by arei** [comment] 2016-10-04 18:37
Here are some thoughts on this issue, but no real answers.  Just putting this here so I remember...

1). Could be a permissions problem. When npmbox runs it first unpacks the .npmbox onto the current working directory.  If for some reason the permissions would prevent npmbox from reading from this file, the npm requests would be made. (unfortunately there is no way to stop npm from trying these requests.)

2). Something to do with the cache timestamps.  Perhaps the unpack process wrote old timestamps for some reason? Generally you will always see the `npm verb get https://registry.npmjs.org/forever` lines, but you should also see `npm verb get https://registry.npmjs.org/forever not expired, no request` if the cached files in the npmbox file were checked and used.

**Comment by igorushko** [comment] 2016-10-12 22:56
```
npmunbox pm2.npmbox -g -v

Unboxing pm2.npmbox...
  Unpacking pm2.npmbox...
  Installing pm2...
npm verb request uri https://registry.npmjs.org/pm2
npm verb request no auth needed
npm info attempt registry request try #1 at 1:54:11 AM
npm verb request id 1b33004d4ddb35cd
npm http request GET https://registry.npmjs.org/pm2
An error occurred while installing pm2.
pm2 was not installed.
{ Error: connect ECONNREFUSED 151.101.12.162:443
    at Object.exports._errnoException (util.js:1026:11)
    at exports._exceptionWithHostPort (util.js:1049:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1085:14)
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '151.101.12.162',
  port: 443 }
  Done.

```

ONLINE:
node: 6.7.0
npm 3.10.9
npmbox 4.0.1
OS: mac sierra

OFFLINE:
node: 6.8.0
npm 3.10.8
npmbox 4.0.1
OS: redhat 7

Also i try on windows and node v4.6.0, maybe something with pm2?

**Comment by danfuzz** [comment] 2016-11-30 21:11
FWIW, I can also confirm that a box of `forever` will not successfully unbox. Node v6.7.0; npm v3.10.8.

**Comment by arei** [comment] 2016-11-30 21:24
Yea, I have recently started seeing this more... I am actively aware of it and looking into it, but time is a finite resource.

**Comment by scorpion14** [comment] 2016-12-05 18:36
I'm having the same problem that igorushko when trying to install pm2 in an offline system using npmbox/npmunbox

This is the output:

Unboxing pm2.npmbox...
  Unpacking pm2.npmbox...
  Installing pm2...
npm verb request uri https://registry.npmjs.org/pm2
npm verb request no auth needed
npm info attempt registry request try #1 at 1:54:11 AM
npm verb request id 1b33004d4ddb35cd
npm http request GET https://registry.npmjs.org/pm2
An error occurred while installing pm2.
pm2 was not installed.
{ Error: connect ETIMEDOUT xxx.xxx.xx.xxx:443
    at Object.exports._errnoException (util.js:1022:11)
    at exports._exceptionWithHostPort (util.js:1045:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1090:14)
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: 'xxx.xxx.xx.xxx',
  port: 443 }
  Done.
Thanks

**Comment by danfuzz** [comment] 2016-12-05 22:16
I did a more digging into this, and I think this may be another problem caused by the `tar.gz` callback getting fired early. My previous fix for this in PR #66 only checks to see if the top-level directory settled but could easily get fooled by subdirectories which take a long time (relatively speaking) to get extracted.

In particular, I'm seeing `npm` decide to make registry requests because it fails to find a cached registry file, e.g. a file like `.npmbox.cache/registry.npmjs.org/some-pkg/.cache.json`. That is, the `fs.stat()` call returns `ENOENT` (file not found). However, inspection of the extracted archive after such a failure (with an intentionally-introduced delay first) shows that the file is indeed there.

I'll try to put together a patch for this (that is, a more complete `tar.gz` bug workaround) tomorrow.

**Comment by danfuzz** [comment] 2016-12-06 15:35
I believe this will be fixed by PR #71 (currently pending).

**Comment by augusto-breowicz** [comment] 2016-12-09 21:25
Same here with tfx-cli:

Unboxing tfx-cli.npmbox...
  Unpacking tfx-cli.npmbox...
  Installing tfx-cli...
npm verb request uri https://registry.npmjs.org/tfx-cli
npm verb request no auth needed
npm info attempt registry request try #1 at 3:25:05 PM
npm verb request id 8c26cb4e3e477774
npm http request GET https://registry.npmjs.org/tfx-cli
An error occurred while installing tfx-cli.
tfx-cli was not installed.
{ [Error: write EPROTO 0:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:782:
] code: 'EPROTO', errno: 'EPROTO', syscall: 'write' }
  Done.

**Comment by scorpion14** [comment] 2016-12-15 00:37
I try the following:
Online computer
1- uninstall npmbox
2- install npmbox
3- create a forever.npmbox ,pm2.npmbox and npmbox.npmbox (i did the cache clean step)
4- copied all files to the offline computer

offline computer
1- uninstall npmbox
2- install npmbox using the site instructions
3- try npmunbox forever (and pm2) => same registry problem as before....

the fix it is working for someone? 

Thanks

**Comment by danfuzz** [comment] 2016-12-20 21:53
Closing this as presumed-fixed by v4.0.2 (just published). Please comment / reopen if you find that the new version is still causing you trouble.

**Closed by danfuzz** 2016-12-20 21:53 UTC

**Comment by TracyBin** [comment] 2017-07-17 07:21
The problem does not seem to be fixed
> npm and node version
```
[root@localhost npmbox]# npm -v
4.1.2
[root@localhost npmbox]# node -v
v7.6.0
```
> npmbox version :v4.2.1

```
[root@localhost npmbox]# npmunbox -v -g forever.npmbox 

Unboxing forever.npmbox...
  Unpacking forever.npmbox...
  Installing forever...
npm verb request uri https://registry.npmjs.org/forever
npm verb request no auth needed
npm info attempt registry request try #1 at 12:17:20 AM
npm verb request id 7182e9df8f92ee1f
npm http request GET https://registry.npmjs.org/forever
An error occurred while installing forever.
forever was not installed.
{ Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'registry.npmjs.org',
  host: 'registry.npmjs.org',
  port: 443 }
  Done.
  { Error: getaddrinfo ENOTFOUND registry.npmjs.org registry.npmjs.org:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)
  code: 'ENOTFOUND',
  errno: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'registry.npmjs.org',
  host: 'registry.npmjs.org',
  port: 443 }
```

**Comment by TracyBin** [comment] 2017-07-17 07:32
/ reopen @danfuzz  Can you reopen this issue?

**Comment by danfuzz** [comment] 2017-07-17 16:23
I couldn't reproduce this (node 8.1.4, npm 4.4.4, npmbox 4.2.1, macOS). @TracyBin what OS are you using, and is it feasible to try to update to a later version of Node and/or npm? (Note: npmbox has trouble npm v5, so stick to the 4.* series.)

I'm not a full-time maintainer of this project, and it seems that Glen (project owner) is also not able to devote a ton of time to it right now, so the more information you can provide about the problem, including digging into the source code, the better the chances are that we can collectively track it down and address it.

**Comment by TracyBin** [comment] 2017-07-18 04:02
@danfuzz Thank you for your time. I will try the latest version.
OS: Centos 7.1.1503
